export const CURRENCY_OPTIONS = [
  { value: 'IDR', label: 'IDR (Rp)' },
  { value: 'USD', label: 'USD ($)' },
  { value: 'EUR', label: 'EUR (€)' },
  { value: 'GBP', label: 'GBP (£)' },
  { value: 'JPY', label: 'JPY (¥)' },
  { value: 'SGD', label: 'SGD (S$)' },
  { value: 'MYR', label: 'MYR (RM)' },
];

export const TIMEZONE_OPTIONS = [
  { value: 'Pacific/Midway', label: 'UTC-11:00 – Midway Island, Samoa' },
  { value: 'Pacific/Honolulu', label: 'UTC-10:00 – Hawaii' },
  { value: 'America/Anchorage', label: 'UTC-09:00 – Alaska' },
  { value: 'America/Los_Angeles', label: 'UTC-08:00 – Pacific Time (US & Canada)' },
  { value: 'America/Denver', label: 'UTC-07:00 – Mountain Time (US & Canada)' },
  { value: 'America/Chicago', label: 'UTC-06:00 – Central Time (US & Canada)' },
  { value: 'America/New_York', label: 'UTC-05:00 – Eastern Time (US & Canada)' },
  { value: 'America/Halifax', label: 'UTC-04:00 – Atlantic Time (Canada)' },
  { value: 'America/Sao_Paulo', label: 'UTC-03:00 – Brasilia, Buenos Aires' },
  { value: 'Atlantic/Azores', label: 'UTC-01:00 – Azores' },
  { value: 'UTC', label: 'UTC+00:00 – UTC, London, Dublin' },
  { value: 'Europe/Paris', label: 'UTC+01:00 – Paris, Berlin, Amsterdam' },
  { value: 'Europe/Athens', label: 'UTC+02:00 – Cairo, Athens, Istanbul' },
  { value: 'Europe/Moscow', label: 'UTC+03:00 – Moscow, Kuwait, Riyadh' },
  { value: 'Asia/Dubai', label: 'UTC+04:00 – Dubai, Abu Dhabi' },
  { value: 'Asia/Karachi', label: 'UTC+05:00 – Karachi, Islamabad' },
  { value: 'Asia/Kolkata', label: 'UTC+05:30 – Chennai, Kolkata, Mumbai, New Delhi' },
  { value: 'Asia/Dhaka', label: 'UTC+06:00 – Dhaka, Astana' },
  { value: 'Asia/Bangkok', label: 'UTC+07:00 – Bangkok, Jakarta (WIB)' },
  { value: 'Asia/Singapore', label: 'UTC+08:00 – Singapore, KL, Manila, Makassar (WITA)' },
  { value: 'Asia/Tokyo', label: 'UTC+09:00 – Tokyo, Seoul, Jayapura (WIT)' },
  { value: 'Australia/Sydney', label: 'UTC+10:00 – Sydney, Melbourne' },
  { value: 'Pacific/Auckland', label: 'UTC+12:00 – Auckland, Wellington' },
];
